[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom domain redirects (update these with your actual Netlify domain)
[[redirects]]
  from = "https://adityakatkoju-portfolio.netlify.app/*"
  to = "https://adityakatkoju-portfolio.netlify.app/:splat"
  status = 200
  force = true

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
